name: ednet_core_tasks
version: 0.0.1

description: ednet_core_tasks application that uses EDNetCore for its model with a many-to-many relationship.

homepage: https://ednet.dev

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ednet_core:
    path: ../../../ednet_cms/packages/ednet_core
  ednet_core_default_app:
    path: ../ednet_core_default_app
